# Generated by Django 4.0.4 on 2022-06-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cp_name', models.CharField(max_length=100)),
                ('cp_country', models.CharField(max_length=50)),
                ('cp_area', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jp_position', models.CharField(max_length=200)),
                ('jp_content', models.TextField()),
                ('jp_technology', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='companys.company')),
            ],
        ),
    ]
