# Generated by Django 4.0.4 on 2022-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='jp_compensation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
